version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    environment:
      - TUNNEL_HOST=backend
      - TUNNEL_PORT=3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - phantom-net

  backend:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - PORT=3000
      - EXTERNAL_PROXY=${EXTERNAL_PROXY}
    command: node --enable-source-maps index.js
    restart: unless-stopped
    networks:
      - phantom-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

networks:
  phantom-net:
    driver: bridge
