name = "phantom-worker"
main = "phantom_worker.js"  # Usa "worker.js" si cambiaste el nombre
compatibility_date = "2024-06-01"

[[kv_namespaces]]
binding = "SESSIONS"
id = "0738e18d82564d06bd1b15c8f4798c40"
