name = "phantom-wo"
main = "worker.js"

account_id = "3e90abd80093fc72e402b32d512d5e39"
compatibility_date = "2025-06-21"

[env.development]
name = "phantom-wo-dev"

[env.production]
name = "phantom-wo-prod"

[vars]
ENVIRONMENT = "production"
